// Generated by scripts/generate-bot-avatar-face-fit.js — do not edit by hand.
//
// For each silhouette: the whole-face scale (s) and offset (dx, dy) at which
// the worst-case face envelope (eyes + mouth) fits fully inside the shape,
// centered in the room the silhouette actually has. Precomputed at build
// time so no geometry is solved at runtime.

import type { BotAvatarAtlasShape } from './bot-avatar.shapes';

const botAvatarFaceFit: Record<BotAvatarAtlasShape, { s: number; dx: number; dy: number }> = {
  circle: { s: 1, dx: 0, dy: 0 },
  square: { s: 1, dx: 0, dy: 0 },
  slanted: { s: 1, dx: 0, dy: 0 },
  arch: { s: 1, dx: 0, dy: 0 },
  'semi-circle': { s: 1, dx: 0, dy: 0 },
  oval: { s: 1, dx: -0.01, dy: 0 },
  pill: { s: 1, dx: -0.01, dy: 0 },
  triangle: { s: 0.96, dx: 0, dy: 0.13 },
  arrow: { s: 0.93, dx: 0, dy: 0.06 },
  fan: { s: 1, dx: -0.07, dy: 0 },
  diamond: { s: 1, dx: 0, dy: 0 },
  'clam-shell': { s: 1, dx: 0, dy: 0 },
  pentagon: { s: 1, dx: 0, dy: 0 },
  gem: { s: 1, dx: 0, dy: 0 },
  'very-sunny': { s: 1, dx: 0, dy: 0 },
  sunny: { s: 1, dx: 0, dy: 0 },
  'cookie-4': { s: 1, dx: 0, dy: 0 },
  'cookie-6': { s: 1, dx: 0, dy: 0 },
  'cookie-7': { s: 1, dx: 0, dy: 0 },
  'cookie-9': { s: 1, dx: 0, dy: 0 },
  'cookie-12': { s: 1, dx: 0, dy: 0 },
  'clover-4': { s: 1, dx: 0, dy: 0 },
  'clover-8': { s: 1, dx: 0.01, dy: 0 },
  burst: { s: 1, dx: 0, dy: 0 },
  'soft-burst': { s: 1, dx: 0, dy: 0 },
  boom: { s: 0.67, dx: 0, dy: -0.01 },
  'soft-boom': { s: 0.92, dx: 0, dy: -0.01 },
  flower: { s: 1, dx: 0, dy: 0 },
  puffy: { s: 1, dx: 0, dy: -0.01 },
  'puffy-diamond': { s: 1, dx: 0, dy: 0 },
  'ghost-ish': { s: 1, dx: 0, dy: 0 },
  'pixel-circle': { s: 1, dx: 0, dy: 0 },
  'pixel-triangle': { s: 0.92, dx: -0.11, dy: -0.04 },
  bun: { s: 1, dx: 0, dy: 0 },
  heart: { s: 0.85, dx: 0, dy: -0.03 },
};

export { botAvatarFaceFit };
