// Generated by scripts/generate-bot-avatar-face-fit.js — do not edit by hand.
//
// For each silhouette: the whole-face scale (s) and vertical offset (dy) at
// which the worst-case face envelope fits fully inside the shape. Two tables:
// eyes only, and eyes + mouth (used whenever the mouth is shown), so mouths
// never poke out of tight silhouettes and eyes-only faces keep their size.
// Precomputed at build time so no geometry is solved at runtime.

import type { BotAvatarShape } from './bot-avatar.shapes';

const botAvatarFaceFit: Record<BotAvatarShape, { s: number; dy: number }> = {
  circle: { s: 1, dy: 0 },
  square: { s: 1, dy: 0 },
  slanted: { s: 1, dy: 0 },
  arch: { s: 1, dy: 0 },
  'semi-circle': { s: 1, dy: 0 },
  oval: { s: 1, dy: 0 },
  pill: { s: 1, dy: 0 },
  triangle: { s: 1, dy: 0.1 },
  arrow: { s: 1, dy: 0.05 },
  fan: { s: 1, dy: 0 },
  diamond: { s: 1, dy: 0 },
  'clam-shell': { s: 1, dy: 0 },
  pentagon: { s: 1, dy: 0 },
  gem: { s: 1, dy: 0 },
  'very-sunny': { s: 1, dy: 0 },
  sunny: { s: 1, dy: 0 },
  'cookie-4': { s: 1, dy: 0 },
  'cookie-6': { s: 1, dy: 0 },
  'cookie-7': { s: 1, dy: 0 },
  'cookie-9': { s: 1, dy: 0 },
  'cookie-12': { s: 1, dy: 0 },
  'clover-4': { s: 1, dy: 0 },
  'clover-8': { s: 1, dy: 0 },
  burst: { s: 1, dy: 0 },
  'soft-burst': { s: 1, dy: 0 },
  boom: { s: 0.85, dy: 0.05 },
  'soft-boom': { s: 1, dy: 0 },
  flower: { s: 1, dy: 0 },
  puffy: { s: 1, dy: 0 },
  'puffy-diamond': { s: 1, dy: 0 },
  'ghost-ish': { s: 1, dy: 0 },
  'pixel-circle': { s: 1, dy: 0 },
  'pixel-triangle': { s: 0.83, dy: 0.06 },
  bun: { s: 1, dy: 0 },
  heart: { s: 1, dy: 0.02 },
};

const botAvatarFaceFitWithMouth: Record<BotAvatarShape, { s: number; dy: number }> = {
  circle: { s: 1, dy: 0 },
  square: { s: 1, dy: 0 },
  slanted: { s: 1, dy: 0 },
  arch: { s: 1, dy: 0 },
  'semi-circle': { s: 1, dy: 0 },
  oval: { s: 1, dy: 0 },
  pill: { s: 1, dy: 0 },
  triangle: { s: 1, dy: 0.1 },
  arrow: { s: 1, dy: 0.05 },
  fan: { s: 1, dy: 0 },
  diamond: { s: 1, dy: 0 },
  'clam-shell': { s: 1, dy: 0 },
  pentagon: { s: 1, dy: 0 },
  gem: { s: 1, dy: 0 },
  'very-sunny': { s: 1, dy: 0 },
  sunny: { s: 1, dy: 0 },
  'cookie-4': { s: 1, dy: 0 },
  'cookie-6': { s: 1, dy: 0 },
  'cookie-7': { s: 1, dy: 0 },
  'cookie-9': { s: 1, dy: 0 },
  'cookie-12': { s: 1, dy: 0 },
  'clover-4': { s: 1, dy: 0 },
  'clover-8': { s: 1, dy: 0 },
  burst: { s: 1, dy: 0 },
  'soft-burst': { s: 1, dy: 0 },
  boom: { s: 0.8, dy: 0.03 },
  'soft-boom': { s: 1, dy: 0 },
  flower: { s: 1, dy: 0 },
  puffy: { s: 1, dy: 0 },
  'puffy-diamond': { s: 1, dy: 0 },
  'ghost-ish': { s: 1, dy: 0 },
  'pixel-circle': { s: 1, dy: 0 },
  'pixel-triangle': { s: 0.8, dy: 0.05 },
  bun: { s: 1, dy: 0 },
  heart: { s: 1, dy: 0.02 },
};

export { botAvatarFaceFit, botAvatarFaceFitWithMouth };
